CREATE TABLE `wp_rg_lead_detail` (  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,  `lead_id` int(10) unsigned NOT NULL,  `form_id` mediumint(8) unsigned NOT NULL,  `field_number` float NOT NULL,  `value` longtext COLLATE utf8mb4_unicode_ci,  PRIMARY KEY (`id`),  KEY `form_id` (`form_id`),  KEY `lead_id` (`lead_id`),  KEY `lead_field_number` (`lead_id`,`field_number`),  KEY `lead_field_value` (`value`(191))) ENGINE=InnoDB AUTO_INCREMENT=174 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40000 ALTER TABLE `wp_rg_lead_detail` DISABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 0;
SET UNIQUE_CHECKS = 0;
INSERT INTO `wp_rg_lead_detail` VALUES('1', '1', '1', '3', 'ghjghj');
INSERT INTO `wp_rg_lead_detail` VALUES('2', '1', '1', '1', '(777) 777-7777');
INSERT INTO `wp_rg_lead_detail` VALUES('3', '1', '1', '4.1', 'Даю согласие на <a href=\"https://euroroaming.ru/obrabotka-personalnyh-dannyh/\" target=\"_blank\" rel=\"noopener nofollow\"><b>обработку персональных данных</b></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('4', '2', '1', '3', 'hgfgh');
INSERT INTO `wp_rg_lead_detail` VALUES('5', '2', '1', '1', '(777) 777-7777');
INSERT INTO `wp_rg_lead_detail` VALUES('6', '2', '1', '4.1', 'Даю согласие на <a href=\"https://euroroaming.ru/obrabotka-personalnyh-dannyh/\" target=\"_blank\" rel=\"noopener nofollow\"><b>обработку персональных данных</b></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('7', '3', '1', '3', 'test');
INSERT INTO `wp_rg_lead_detail` VALUES('8', '3', '1', '1', '(123) 111-1111');
INSERT INTO `wp_rg_lead_detail` VALUES('9', '3', '1', '4.1', 'Даю согласие на <a href=\"#\" target=\"_blank\" rel=\"noopener nofollow\"><b>обработку персональных данных</b></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('10', '4', '1', '3', 'test7');
INSERT INTO `wp_rg_lead_detail` VALUES('11', '4', '1', '1', '(123) 111-1111');
INSERT INTO `wp_rg_lead_detail` VALUES('12', '4', '1', '4.1', 'Даю согласие на <a href=\"#\" target=\"_blank\" rel=\"noopener nofollow\"><b>обработку персональных данных</b></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('13', '5', '1', '3', 'test9');
INSERT INTO `wp_rg_lead_detail` VALUES('14', '5', '1', '1', '(123) 111-1111');
INSERT INTO `wp_rg_lead_detail` VALUES('15', '5', '1', '4.1', 'Даю согласие на <a href=\"#\" target=\"_blank\" rel=\"noopener nofollow\"><b>обработку персональных данных</b></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('16', '6', '1', '3', 'test11111');
INSERT INTO `wp_rg_lead_detail` VALUES('17', '6', '1', '1', '(123) 111-1111');
INSERT INTO `wp_rg_lead_detail` VALUES('18', '6', '1', '4.1', 'Даю согласие на <a href=\"#\" target=\"_blank\" rel=\"noopener nofollow\"><b>обработку персональных данных</b></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('19', '7', '1', '3', 'testclient');
INSERT INTO `wp_rg_lead_detail` VALUES('20', '7', '1', '1', '(123) 123-1231');
INSERT INTO `wp_rg_lead_detail` VALUES('21', '7', '1', '4.1', 'Даю согласие на <a href=\"#\" target=\"_blank\" rel=\"noopener nofollow\"><b>обработку персональных данных</b></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('22', '8', '2', '2', 'dfgdfg@dfgdfg.ru');
INSERT INTO `wp_rg_lead_detail` VALUES('23', '8', '2', '7', 'fghfgh');
INSERT INTO `wp_rg_lead_detail` VALUES('24', '9', '1', '3', 'Евгений');
INSERT INTO `wp_rg_lead_detail` VALUES('25', '9', '1', '1', '(962) 826-5660');
INSERT INTO `wp_rg_lead_detail` VALUES('26', '9', '1', '4.1', 'Даю согласие на <a href=\"#\" target=\"_blank\" rel=\"noopener nofollow\"><b>обработку персональных данных</b></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('27', '10', '1', '3', 'Наталья');
INSERT INTO `wp_rg_lead_detail` VALUES('28', '10', '1', '1', '(917) 745-5401');
INSERT INTO `wp_rg_lead_detail` VALUES('29', '10', '1', '4.1', 'Даю согласие на <a href=\"#\" target=\"_blank\" rel=\"noopener nofollow\"><b>обработку персональных данных</b></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('30', '11', '2', '4', 'test0');
INSERT INTO `wp_rg_lead_detail` VALUES('31', '11', '2', '2', 'test0@test0.ru');
INSERT INTO `wp_rg_lead_detail` VALUES('32', '11', '2', '7', 'dfgjfgh fdgjgfhj');
INSERT INTO `wp_rg_lead_detail` VALUES('33', '11', '2', '9.1', 'Даю согласие на <a href=\"#\" target=\"_blank\" rel=\"noopener nofollow\"><b>обработку персональных данных</b></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('34', '12', '1', '3', 'Александр');
INSERT INTO `wp_rg_lead_detail` VALUES('35', '12', '1', '1', '(916) 362-9256');
INSERT INTO `wp_rg_lead_detail` VALUES('36', '12', '1', '4.1', 'Даю согласие на <a href=\"#\" target=\"_blank\" rel=\"noopener nofollow\"><b>обработку персональных данных</b></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('37', '13', '1', '3', 'Дарья');
INSERT INTO `wp_rg_lead_detail` VALUES('38', '13', '1', '1', '(916) 157-5945');
INSERT INTO `wp_rg_lead_detail` VALUES('39', '13', '1', '4.1', 'Даю согласие на <a href=\"#\" target=\"_blank\" rel=\"noopener nofollow\"><b>обработку персональных данных</b></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('40', '14', '1', '3', 'Александр');
INSERT INTO `wp_rg_lead_detail` VALUES('41', '14', '1', '1', '(903) 736-5533');
INSERT INTO `wp_rg_lead_detail` VALUES('42', '14', '1', '4.1', 'Даю согласие на <a href=\"#\" target=\"_blank\" rel=\"noopener nofollow\"><b>обработку персональных данных</b></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('43', '15', '1', '3', 'вадим');
INSERT INTO `wp_rg_lead_detail` VALUES('44', '15', '1', '1', '(929) 661-2771');
INSERT INTO `wp_rg_lead_detail` VALUES('45', '15', '1', '4.1', 'Даю согласие на <a href=\"#\" target=\"_blank\" rel=\"noopener nofollow\"><b>обработку персональных данных</b></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('46', '16', '2', '4', 'Антон');
INSERT INTO `wp_rg_lead_detail` VALUES('47', '16', '2', '2', 'antony.tailor@gmail.com');
INSERT INTO `wp_rg_lead_detail` VALUES('48', '16', '2', '7', 'Добрый вечер!\r\nЗаказал у вас 2 симки 26.03.18 На сайте пришло подтверждение, заказ 1400. На почту ничего не пришло. Могу ли я рассчитывать на своевременное получения заказа?\r\nСпасибо!');
INSERT INTO `wp_rg_lead_detail` VALUES('49', '16', '2', '9.1', 'Даю согласие на <a href=\"#\" target=\"_blank\" rel=\"noopener nofollow\"><b>обработку персональных данных</b></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('50', '17', '1', '3', 'Анастасия');
INSERT INTO `wp_rg_lead_detail` VALUES('51', '17', '1', '1', '(968) 710-3063');
INSERT INTO `wp_rg_lead_detail` VALUES('52', '17', '1', '4.1', 'Даю согласие на <a href=\"#\" target=\"_blank\" rel=\"noopener nofollow\"><b>обработку персональных данных</b></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('53', '18', '2', '4', 'Илья');
INSERT INTO `wp_rg_lead_detail` VALUES('54', '18', '2', '2', 'ilia.bogdanov@rambler.ru');
INSERT INTO `wp_rg_lead_detail` VALUES('55', '18', '2', '7', 'Здравствуйте! Подскажите, как осуществляется оплата и доставка (в г. Ростов-на-Дону).\r\nСпасибо.');
INSERT INTO `wp_rg_lead_detail` VALUES('56', '18', '2', '9.1', 'Даю согласие на <a href=\"#\" target=\"_blank\" rel=\"noopener nofollow\"><b>обработку персональных данных</b></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('57', '19', '1', '3', 'Алексей');
INSERT INTO `wp_rg_lead_detail` VALUES('58', '19', '1', '1', '(920) 561-0211');
INSERT INTO `wp_rg_lead_detail` VALUES('59', '19', '1', '4.1', 'Даю согласие на <a href=\"#\" target=\"_blank\" rel=\"noopener nofollow\"><b>обработку персональных данных</b></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('60', '20', '1', '3', 'Дмитрий');
INSERT INTO `wp_rg_lead_detail` VALUES('61', '20', '1', '1', '(961) 793-3850');
INSERT INTO `wp_rg_lead_detail` VALUES('62', '20', '1', '4.1', 'Даю согласие на <a href=\"#\" target=\"_blank\" rel=\"noopener nofollow\"><b>обработку персональных данных</b></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('63', '21', '1', '3', 'Анастасия');
INSERT INTO `wp_rg_lead_detail` VALUES('64', '21', '1', '1', '(968) 710-3063');
INSERT INTO `wp_rg_lead_detail` VALUES('65', '21', '1', '4.1', 'Даю согласие на обработку персональных данных<a></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('66', '22', '1', '3', 'Владимир');
INSERT INTO `wp_rg_lead_detail` VALUES('67', '22', '1', '1', '(916) 653-1669');
INSERT INTO `wp_rg_lead_detail` VALUES('68', '22', '1', '4.1', 'Даю согласие на обработку персональных данных<a></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('69', '23', '1', '3', 'Владимир');
INSERT INTO `wp_rg_lead_detail` VALUES('70', '23', '1', '1', '(916) 653-1669');
INSERT INTO `wp_rg_lead_detail` VALUES('71', '23', '1', '4.1', 'Даю согласие на обработку персональных данных<a></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('72', '24', '2', '4', 'Азат');
INSERT INTO `wp_rg_lead_detail` VALUES('73', '24', '2', '2', 'azatfa@yandex.ru');
INSERT INTO `wp_rg_lead_detail` VALUES('74', '24', '2', '7', 'Здравствуйте!\r\nнужна сим карта для поездки в Испанию. период использования с 09.04.2018 по 19.05.2018\r\nХотел узнать как будет активирована карта (каким числом?) если купить ее у вас с тарифом 2 Гб и пополнив баланс на 20 евро?\r\nКогда смогу получить/забрать карту если закажу ее сегодня?\r\nСпасибо!');
INSERT INTO `wp_rg_lead_detail` VALUES('75', '24', '2', '9.1', 'Даю согласие на обработку персональных данных *');
INSERT INTO `wp_rg_lead_detail` VALUES('76', '25', '1', '3', 'Азат');
INSERT INTO `wp_rg_lead_detail` VALUES('77', '25', '1', '1', '(916) 576-6510');
INSERT INTO `wp_rg_lead_detail` VALUES('78', '25', '1', '4.1', 'Даю согласие на обработку персональных данных<a></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('79', '26', '2', '2', 'azatfa@yandex.ru');
INSERT INTO `wp_rg_lead_detail` VALUES('80', '26', '2', '7', 'никак не получается оформить заказ');
INSERT INTO `wp_rg_lead_detail` VALUES('81', '26', '2', '9.1', 'Даю согласие на обработку персональных данных *');
INSERT INTO `wp_rg_lead_detail` VALUES('82', '27', '1', '3', 'Сергей');
INSERT INTO `wp_rg_lead_detail` VALUES('83', '27', '1', '1', '(977) 410-7141');
INSERT INTO `wp_rg_lead_detail` VALUES('84', '27', '1', '4.1', 'Даю согласие на обработку персональных данных<a></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('85', '28', '1', '3', 'Анастасия');
INSERT INTO `wp_rg_lead_detail` VALUES('86', '28', '1', '1', '(968) 710-3063');
INSERT INTO `wp_rg_lead_detail` VALUES('87', '28', '1', '4.1', 'Даю согласие на обработку персональных данных<a></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('88', '29', '1', '3', 'Анастасия');
INSERT INTO `wp_rg_lead_detail` VALUES('89', '29', '1', '1', '(985) 290-8455');
INSERT INTO `wp_rg_lead_detail` VALUES('90', '29', '1', '4.1', 'Даю согласие на обработку персональных данных<a></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('91', '30', '1', '3', 'Александр');
INSERT INTO `wp_rg_lead_detail` VALUES('92', '30', '1', '1', '(962) 989-2926');
INSERT INTO `wp_rg_lead_detail` VALUES('93', '30', '1', '4.1', 'Даю согласие на обработку персональных данных<a></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('94', '31', '1', '3', 'Владимир');
INSERT INTO `wp_rg_lead_detail` VALUES('95', '31', '1', '1', '(916) 653-1669');
INSERT INTO `wp_rg_lead_detail` VALUES('96', '31', '1', '4.1', 'Даю согласие на обработку персональных данных<a></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('97', '32', '1', '3', 'Владимир');
INSERT INTO `wp_rg_lead_detail` VALUES('98', '32', '1', '1', '(916) 653-1669');
INSERT INTO `wp_rg_lead_detail` VALUES('99', '32', '1', '4.1', 'Даю согласие на обработку персональных данных<a></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('100', '33', '1', '3', 'Алексей');
INSERT INTO `wp_rg_lead_detail` VALUES('101', '33', '1', '1', '(916) 195-0256');
INSERT INTO `wp_rg_lead_detail` VALUES('102', '33', '1', '4.1', 'Даю согласие на обработку персональных данных<a></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('103', '34', '1', '3', 'Маргарита');
INSERT INTO `wp_rg_lead_detail` VALUES('104', '34', '1', '1', '(978) 826-4533');
INSERT INTO `wp_rg_lead_detail` VALUES('105', '34', '1', '4.1', 'Даю согласие на обработку персональных данных<a></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('106', '35', '1', '3', 'Алексей');
INSERT INTO `wp_rg_lead_detail` VALUES('107', '35', '1', '1', '(916) 195-0256');
INSERT INTO `wp_rg_lead_detail` VALUES('108', '35', '1', '4.1', 'Даю согласие на обработку персональных данных<a></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('109', '36', '1', '3', 'Дмитрий');
INSERT INTO `wp_rg_lead_detail` VALUES('110', '36', '1', '1', '(961) 793-3850');
INSERT INTO `wp_rg_lead_detail` VALUES('111', '36', '1', '4.1', 'Даю согласие на обработку персональных данных<a></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('112', '37', '1', '3', 'Дарья');
INSERT INTO `wp_rg_lead_detail` VALUES('113', '37', '1', '1', '(916) 739-4548');
INSERT INTO `wp_rg_lead_detail` VALUES('114', '37', '1', '4.1', 'Даю согласие на обработку персональных данных<a></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('115', '38', '2', '4', 'Дарья Дюженкова');
INSERT INTO `wp_rg_lead_detail` VALUES('116', '38', '2', '2', 'danyasha_77@mail.ru');
INSERT INTO `wp_rg_lead_detail` VALUES('117', '38', '2', '7', 'Добрый день! Вчера оформила заказ № R83112. Мне перезвонили и попросили на почту info@orangesim.ru отправить скан моего загранпаспорта. Я письмо написала, но оно не доходит до адресата, почта Mail.ru пишет что не удается доставить письмо. Что делать?');
INSERT INTO `wp_rg_lead_detail` VALUES('118', '38', '2', '9.1', 'Даю согласие на обработку персональных данных *');
INSERT INTO `wp_rg_lead_detail` VALUES('119', '39', '1', '3', 'Дмитрий');
INSERT INTO `wp_rg_lead_detail` VALUES('120', '39', '1', '1', '(961) 793-3850');
INSERT INTO `wp_rg_lead_detail` VALUES('121', '39', '1', '4.1', 'Даю согласие на обработку персональных данных<a></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('122', '40', '2', '4', 'Ирина');
INSERT INTO `wp_rg_lead_detail` VALUES('123', '40', '2', '2', 'jarinka111@yandex.ru');
INSERT INTO `wp_rg_lead_detail` VALUES('124', '40', '2', '7', 'Добрый вечер! В корзине заказ находится, а оформить не получается, автоматически перекидывает на сат. Почему?');
INSERT INTO `wp_rg_lead_detail` VALUES('125', '40', '2', '9.1', 'Даю согласие на обработку персональных данных *');
INSERT INTO `wp_rg_lead_detail` VALUES('126', '41', '1', '3', 'Василий');
INSERT INTO `wp_rg_lead_detail` VALUES('127', '41', '1', '1', '(906) 127-0118');
INSERT INTO `wp_rg_lead_detail` VALUES('128', '41', '1', '4.1', 'Даю согласие на обработку персональных данных<a></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('129', '42', '1', '3', 'Сергей');
INSERT INTO `wp_rg_lead_detail` VALUES('130', '42', '1', '1', '(958) 535-2510');
INSERT INTO `wp_rg_lead_detail` VALUES('131', '42', '1', '4.1', 'Даю согласие на обработку персональных данных<a></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('132', '43', '1', '3', 'Анастасия');
INSERT INTO `wp_rg_lead_detail` VALUES('133', '43', '1', '1', '(968) 710-3063');
INSERT INTO `wp_rg_lead_detail` VALUES('134', '43', '1', '4.1', 'Даю согласие на обработку персональных данных<a></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('135', '44', '1', '3', 'Дарья');
INSERT INTO `wp_rg_lead_detail` VALUES('136', '44', '1', '1', '(920) 430-8700');
INSERT INTO `wp_rg_lead_detail` VALUES('137', '44', '1', '4.1', 'Даю согласие на обработку персональных данных<a></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('138', '45', '2', '4', 'Кирилл');
INSERT INTO `wp_rg_lead_detail` VALUES('139', '45', '2', '2', 'koloskovy@mail.ru');
INSERT INTO `wp_rg_lead_detail` VALUES('140', '45', '2', '7', 'Интересует интернет 15 евро за 6 ГБ\r\nЗабрать удобно в Одинцово');
INSERT INTO `wp_rg_lead_detail` VALUES('141', '45', '2', '9.1', 'Даю согласие на обработку персональных данных *');
INSERT INTO `wp_rg_lead_detail` VALUES('142', '46', '1', '3', 'Кирилл');
INSERT INTO `wp_rg_lead_detail` VALUES('143', '46', '1', '1', '(926) 332-9088');
INSERT INTO `wp_rg_lead_detail` VALUES('144', '46', '1', '4.1', 'Даю согласие на обработку персональных данных<a></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('145', '47', '1', '3', 'Ольга');
INSERT INTO `wp_rg_lead_detail` VALUES('146', '47', '1', '1', '(908) 024-4970');
INSERT INTO `wp_rg_lead_detail` VALUES('147', '47', '1', '4.1', 'Даю согласие на обработку персональных данных<a></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('148', '48', '1', '3', 'Ольга');
INSERT INTO `wp_rg_lead_detail` VALUES('149', '48', '1', '1', '(908) 024-4970');
INSERT INTO `wp_rg_lead_detail` VALUES('150', '48', '1', '4.1', 'Даю согласие на обработку персональных данных<a></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('151', '49', '1', '3', 'олег рудольфович');
INSERT INTO `wp_rg_lead_detail` VALUES('152', '49', '1', '1', '(967) 196-2882');
INSERT INTO `wp_rg_lead_detail` VALUES('153', '49', '1', '4.1', 'Даю согласие на обработку персональных данных<a></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('154', '50', '1', '3', 'Иван');
INSERT INTO `wp_rg_lead_detail` VALUES('155', '50', '1', '1', '(981) 715-1450');
INSERT INTO `wp_rg_lead_detail` VALUES('156', '50', '1', '4.1', 'Даю согласие на обработку персональных данных<a></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('157', '51', '1', '3', 'Светлана');
INSERT INTO `wp_rg_lead_detail` VALUES('158', '51', '1', '1', '(915) 023-9313');
INSERT INTO `wp_rg_lead_detail` VALUES('159', '51', '1', '4.1', 'Даю согласие на обработку персональных данных<a></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('160', '52', '1', '3', 'Олег Рудольфович');
INSERT INTO `wp_rg_lead_detail` VALUES('161', '52', '1', '1', '(967) 196-2882');
INSERT INTO `wp_rg_lead_detail` VALUES('162', '52', '1', '4.1', 'Даю согласие на обработку персональных данных<a></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('163', '53', '2', '4', 'Сергей');
INSERT INTO `wp_rg_lead_detail` VALUES('164', '53', '2', '2', 'artist-rest@ya.ru');
INSERT INTO `wp_rg_lead_detail` VALUES('165', '53', '2', '7', 'Сколько по времени будет доставка карты в Ростов -на-Дону? И есть ли возможность забрать карту рано утром в аэропорту Шереметьево?');
INSERT INTO `wp_rg_lead_detail` VALUES('166', '53', '2', '9.1', 'Даю согласие на обработку персональных данных *');
INSERT INTO `wp_rg_lead_detail` VALUES('167', '54', '1', '3', 'Сергей');
INSERT INTO `wp_rg_lead_detail` VALUES('168', '54', '1', '1', '(918) 558-4836');
INSERT INTO `wp_rg_lead_detail` VALUES('169', '54', '1', '4.1', 'Даю согласие на обработку персональных данных<a></a>');
INSERT INTO `wp_rg_lead_detail` VALUES('170', '55', '2', '4', 'Екатерина');
INSERT INTO `wp_rg_lead_detail` VALUES('171', '55', '2', '2', 'larsi@mail.ru');
INSERT INTO `wp_rg_lead_detail` VALUES('172', '55', '2', '7', 'Добрый день. Хочу приотрести сим-карту в Москве. На сайте при оформлении заказа не нашла московские пункты выдачи. \r\nКак можно купить карту с получением в пункте выдачи?');
INSERT INTO `wp_rg_lead_detail` VALUES('173', '55', '2', '9.1', 'Даю согласие на обработку персональных данных *');
/*!40000 ALTER TABLE `wp_rg_lead_detail` ENABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS = 1;
