CREATE TABLE `wp_term_taxonomy` (  `term_taxonomy_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,  `term_id` bigint(20) unsigned NOT NULL DEFAULT '0',  `taxonomy` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',  `description` longtext COLLATE utf8mb4_unicode_ci NOT NULL,  `parent` bigint(20) unsigned NOT NULL DEFAULT '0',  `count` bigint(20) NOT NULL DEFAULT '0',  PRIMARY KEY (`term_taxonomy_id`),  UNIQUE KEY `term_id_taxonomy` (`term_id`,`taxonomy`),  KEY `taxonomy` (`taxonomy`)) ENGINE=InnoDB AUTO_INCREMENT=49 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40000 ALTER TABLE `wp_term_taxonomy` DISABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 0;
SET UNIQUE_CHECKS = 0;
INSERT INTO `wp_term_taxonomy` VALUES('1', '1', 'category', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('2', '2', 'category', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('3', '3', 'category', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('4', '4', 'category', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('5', '5', 'category', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('6', '6', 'category', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('7', '7', 'category', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('8', '8', 'post_tag', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('9', '9', 'post_tag', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('10', '10', 'post_tag', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('11', '11', 'post_tag', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('12', '12', 'post_tag', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('13', '13', 'post_tag', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('14', '14', 'post_tag', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('15', '15', 'post_tag', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('16', '16', 'post_tag', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('17', '17', 'post_tag', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('18', '18', 'post_tag', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('19', '19', 'post_tag', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('20', '20', 'post_tag', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('21', '21', 'post_tag', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('22', '22', 'post_tag', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('23', '23', 'post_tag', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('24', '24', 'nav_menu', '', '0', '22');
INSERT INTO `wp_term_taxonomy` VALUES('25', '25', 'product_type', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('26', '26', 'product_type', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('28', '28', 'product_type', '', '0', '2');
INSERT INTO `wp_term_taxonomy` VALUES('29', '29', 'product_type', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('30', '30', 'product_type', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('31', '31', 'product_visibility', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('33', '33', 'product_visibility', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('34', '34', 'product_visibility', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('36', '36', 'product_visibility', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('37', '37', 'product_visibility', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('39', '39', 'product_visibility', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('41', '41', 'product_visibility', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('42', '42', 'product_visibility', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('44', '44', 'product_visibility', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('45', '45', 'product_visibility', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('47', '46', 'product_cat', '', '0', '0');
INSERT INTO `wp_term_taxonomy` VALUES('48', '47', 'nav_menu', '', '0', '6');
/*!40000 ALTER TABLE `wp_term_taxonomy` ENABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS = 1;
