CREATE TABLE `wp_term_relationships` (  `object_id` bigint(20) unsigned NOT NULL DEFAULT '0',  `term_taxonomy_id` bigint(20) unsigned NOT NULL DEFAULT '0',  `term_order` int(11) NOT NULL DEFAULT '0',  PRIMARY KEY (`object_id`,`term_taxonomy_id`),  KEY `term_taxonomy_id` (`term_taxonomy_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40000 ALTER TABLE `wp_term_relationships` DISABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 0;
SET UNIQUE_CHECKS = 0;
INSERT INTO `wp_term_relationships` VALUES('1034', '24', '0');
INSERT INTO `wp_term_relationships` VALUES('1035', '24', '0');
INSERT INTO `wp_term_relationships` VALUES('1036', '24', '0');
INSERT INTO `wp_term_relationships` VALUES('1037', '24', '0');
INSERT INTO `wp_term_relationships` VALUES('1038', '24', '0');
INSERT INTO `wp_term_relationships` VALUES('1039', '24', '0');
INSERT INTO `wp_term_relationships` VALUES('1040', '24', '0');
INSERT INTO `wp_term_relationships` VALUES('1041', '24', '0');
INSERT INTO `wp_term_relationships` VALUES('1042', '24', '0');
INSERT INTO `wp_term_relationships` VALUES('1099', '24', '0');
INSERT INTO `wp_term_relationships` VALUES('1201', '24', '0');
INSERT INTO `wp_term_relationships` VALUES('1202', '24', '0');
INSERT INTO `wp_term_relationships` VALUES('1203', '24', '0');
INSERT INTO `wp_term_relationships` VALUES('1204', '24', '0');
INSERT INTO `wp_term_relationships` VALUES('1205', '24', '0');
INSERT INTO `wp_term_relationships` VALUES('1206', '24', '0');
INSERT INTO `wp_term_relationships` VALUES('1207', '24', '0');
INSERT INTO `wp_term_relationships` VALUES('1208', '24', '0');
INSERT INTO `wp_term_relationships` VALUES('1209', '24', '0');
INSERT INTO `wp_term_relationships` VALUES('1210', '24', '0');
INSERT INTO `wp_term_relationships` VALUES('1258', '24', '0');
INSERT INTO `wp_term_relationships` VALUES('1259', '24', '0');
INSERT INTO `wp_term_relationships` VALUES('1346', '28', '0');
INSERT INTO `wp_term_relationships` VALUES('1395', '28', '0');
INSERT INTO `wp_term_relationships` VALUES('83203', '48', '0');
INSERT INTO `wp_term_relationships` VALUES('83204', '48', '0');
INSERT INTO `wp_term_relationships` VALUES('83205', '48', '0');
INSERT INTO `wp_term_relationships` VALUES('83206', '48', '0');
INSERT INTO `wp_term_relationships` VALUES('83207', '48', '0');
INSERT INTO `wp_term_relationships` VALUES('83209', '48', '0');
/*!40000 ALTER TABLE `wp_term_relationships` ENABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS = 1;
