CREATE TABLE `wp_woocommerce_order_items` (  `order_item_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,  `order_item_name` text COLLATE utf8mb4_unicode_ci NOT NULL,  `order_item_type` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',  `order_id` bigint(20) unsigned NOT NULL,  PRIMARY KEY (`order_item_id`),  KEY `order_id` (`order_id`)) ENGINE=InnoDB AUTO_INCREMENT=270 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40000 ALTER TABLE `wp_woocommerce_order_items` DISABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 0;
SET UNIQUE_CHECKS = 0;
INSERT INTO `wp_woocommerce_order_items` VALUES('1', 'Сим-карта Orange с тарифом Mundo', 'line_item', '1399');
INSERT INTO `wp_woocommerce_order_items` VALUES('2', 'Бесплатная доставка', 'shipping', '1399');
INSERT INTO `wp_woocommerce_order_items` VALUES('3', 'Сим-карта Orange с тарифом Mundo', 'line_item', '1400');
INSERT INTO `wp_woocommerce_order_items` VALUES('4', 'Бесплатная доставка', 'shipping', '1400');
INSERT INTO `wp_woocommerce_order_items` VALUES('5', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83019');
INSERT INTO `wp_woocommerce_order_items` VALUES('6', 'Курьерская служба доставки: Москва, Москва', 'shipping', '83019');
INSERT INTO `wp_woocommerce_order_items` VALUES('7', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83022');
INSERT INTO `wp_woocommerce_order_items` VALUES('8', 'Бесплатная доставка (Почта РФ)', 'shipping', '83022');
INSERT INTO `wp_woocommerce_order_items` VALUES('9', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83023');
INSERT INTO `wp_woocommerce_order_items` VALUES('10', 'Бесплатная доставка (Почта РФ)', 'shipping', '83023');
INSERT INTO `wp_woocommerce_order_items` VALUES('11', '', 'line_item', '83024');
INSERT INTO `wp_woocommerce_order_items` VALUES('12', '', 'line_item', '83024');
INSERT INTO `wp_woocommerce_order_items` VALUES('13', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83102');
INSERT INTO `wp_woocommerce_order_items` VALUES('14', 'Пункт выдачи: бесплатно', 'shipping', '83102');
INSERT INTO `wp_woocommerce_order_items` VALUES('15', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83103');
INSERT INTO `wp_woocommerce_order_items` VALUES('16', 'Пункт выдачи: бесплатно', 'shipping', '83103');
INSERT INTO `wp_woocommerce_order_items` VALUES('17', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83104');
INSERT INTO `wp_woocommerce_order_items` VALUES('18', 'Пункт выдачи: бесплатно', 'shipping', '83104');
INSERT INTO `wp_woocommerce_order_items` VALUES('19', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83108');
INSERT INTO `wp_woocommerce_order_items` VALUES('20', 'Бесплатная доставка (Почта РФ)', 'shipping', '83108');
INSERT INTO `wp_woocommerce_order_items` VALUES('21', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83109');
INSERT INTO `wp_woocommerce_order_items` VALUES('22', 'Курьером до двери', 'shipping', '83109');
INSERT INTO `wp_woocommerce_order_items` VALUES('23', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83110');
INSERT INTO `wp_woocommerce_order_items` VALUES('24', 'Бесплатная доставка (Почта РФ)', 'shipping', '83110');
INSERT INTO `wp_woocommerce_order_items` VALUES('25', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83111');
INSERT INTO `wp_woocommerce_order_items` VALUES('26', 'Бесплатная доставка (Почта РФ)', 'shipping', '83111');
INSERT INTO `wp_woocommerce_order_items` VALUES('27', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83112');
INSERT INTO `wp_woocommerce_order_items` VALUES('28', 'Бесплатная доставка (Почта РФ)', 'shipping', '83112');
INSERT INTO `wp_woocommerce_order_items` VALUES('29', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83115');
INSERT INTO `wp_woocommerce_order_items` VALUES('30', 'Курьерская служба доставки: г Москва, Москва', 'shipping', '83115');
INSERT INTO `wp_woocommerce_order_items` VALUES('31', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83116');
INSERT INTO `wp_woocommerce_order_items` VALUES('32', 'Пункт выдачи: бесплатно', 'shipping', '83116');
INSERT INTO `wp_woocommerce_order_items` VALUES('35', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83119');
INSERT INTO `wp_woocommerce_order_items` VALUES('36', 'Пункт выдачи: бесплатно', 'shipping', '83119');
INSERT INTO `wp_woocommerce_order_items` VALUES('39', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83120');
INSERT INTO `wp_woocommerce_order_items` VALUES('40', 'Курьером до двери', 'shipping', '83120');
INSERT INTO `wp_woocommerce_order_items` VALUES('57', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83121');
INSERT INTO `wp_woocommerce_order_items` VALUES('58', 'Пункт выдачи: бесплатно', 'shipping', '83121');
INSERT INTO `wp_woocommerce_order_items` VALUES('61', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83122');
INSERT INTO `wp_woocommerce_order_items` VALUES('62', 'Бесплатная доставка (Почта РФ)', 'shipping', '83122');
INSERT INTO `wp_woocommerce_order_items` VALUES('63', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83123');
INSERT INTO `wp_woocommerce_order_items` VALUES('64', 'Курьером до двери', 'shipping', '83123');
INSERT INTO `wp_woocommerce_order_items` VALUES('67', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83124');
INSERT INTO `wp_woocommerce_order_items` VALUES('68', 'Пункт выдачи: бесплатно', 'shipping', '83124');
INSERT INTO `wp_woocommerce_order_items` VALUES('77', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83125');
INSERT INTO `wp_woocommerce_order_items` VALUES('78', 'Пункт выдачи: бесплатно', 'shipping', '83125');
INSERT INTO `wp_woocommerce_order_items` VALUES('81', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83126');
INSERT INTO `wp_woocommerce_order_items` VALUES('82', 'Бесплатная доставка (Почта РФ)', 'shipping', '83126');
INSERT INTO `wp_woocommerce_order_items` VALUES('83', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83127');
INSERT INTO `wp_woocommerce_order_items` VALUES('84', 'Бесплатная доставка (Почта РФ)', 'shipping', '83127');
INSERT INTO `wp_woocommerce_order_items` VALUES('87', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83128');
INSERT INTO `wp_woocommerce_order_items` VALUES('88', 'Бесплатная доставка (Почта РФ)', 'shipping', '83128');
INSERT INTO `wp_woocommerce_order_items` VALUES('89', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83129');
INSERT INTO `wp_woocommerce_order_items` VALUES('90', 'Бесплатная доставка (Почта РФ)', 'shipping', '83129');
INSERT INTO `wp_woocommerce_order_items` VALUES('91', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83130');
INSERT INTO `wp_woocommerce_order_items` VALUES('92', 'Бесплатная доставка (Почта РФ)', 'shipping', '83130');
INSERT INTO `wp_woocommerce_order_items` VALUES('95', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83131');
INSERT INTO `wp_woocommerce_order_items` VALUES('96', 'Пункт выдачи: бесплатно', 'shipping', '83131');
INSERT INTO `wp_woocommerce_order_items` VALUES('97', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83132');
INSERT INTO `wp_woocommerce_order_items` VALUES('98', 'Бесплатная доставка (Почта РФ)', 'shipping', '83132');
INSERT INTO `wp_woocommerce_order_items` VALUES('99', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83133');
INSERT INTO `wp_woocommerce_order_items` VALUES('100', 'Бесплатная доставка (Почта РФ)', 'shipping', '83133');
INSERT INTO `wp_woocommerce_order_items` VALUES('101', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83134');
INSERT INTO `wp_woocommerce_order_items` VALUES('102', 'Бесплатная доставка (Почта РФ)', 'shipping', '83134');
INSERT INTO `wp_woocommerce_order_items` VALUES('103', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83135');
INSERT INTO `wp_woocommerce_order_items` VALUES('104', 'Бесплатная доставка (Почта РФ)', 'shipping', '83135');
INSERT INTO `wp_woocommerce_order_items` VALUES('105', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83136');
INSERT INTO `wp_woocommerce_order_items` VALUES('106', 'Бесплатная доставка (Почта РФ)', 'shipping', '83136');
INSERT INTO `wp_woocommerce_order_items` VALUES('107', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83137');
INSERT INTO `wp_woocommerce_order_items` VALUES('108', 'Бесплатная доставка (Почта РФ)', 'shipping', '83137');
INSERT INTO `wp_woocommerce_order_items` VALUES('109', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83138');
INSERT INTO `wp_woocommerce_order_items` VALUES('110', 'Бесплатная доставка (Почта РФ)', 'shipping', '83138');
INSERT INTO `wp_woocommerce_order_items` VALUES('111', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83139');
INSERT INTO `wp_woocommerce_order_items` VALUES('112', 'Бесплатная доставка (Почта РФ)', 'shipping', '83139');
INSERT INTO `wp_woocommerce_order_items` VALUES('113', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83140');
INSERT INTO `wp_woocommerce_order_items` VALUES('114', 'Бесплатная доставка (Почта РФ)', 'shipping', '83140');
INSERT INTO `wp_woocommerce_order_items` VALUES('115', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83141');
INSERT INTO `wp_woocommerce_order_items` VALUES('116', 'Бесплатная доставка (Почта РФ)', 'shipping', '83141');
INSERT INTO `wp_woocommerce_order_items` VALUES('117', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83142');
INSERT INTO `wp_woocommerce_order_items` VALUES('118', 'Бесплатная доставка (Почта РФ)', 'shipping', '83142');
INSERT INTO `wp_woocommerce_order_items` VALUES('119', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83143');
INSERT INTO `wp_woocommerce_order_items` VALUES('120', 'Бесплатная доставка (Почта РФ)', 'shipping', '83143');
INSERT INTO `wp_woocommerce_order_items` VALUES('121', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83144');
INSERT INTO `wp_woocommerce_order_items` VALUES('122', 'Бесплатная доставка (Почта РФ)', 'shipping', '83144');
INSERT INTO `wp_woocommerce_order_items` VALUES('123', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83145');
INSERT INTO `wp_woocommerce_order_items` VALUES('124', 'Пункт выдачи: бесплатно', 'shipping', '83145');
INSERT INTO `wp_woocommerce_order_items` VALUES('125', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83146');
INSERT INTO `wp_woocommerce_order_items` VALUES('126', 'Пункт выдачи: бесплатно', 'shipping', '83146');
INSERT INTO `wp_woocommerce_order_items` VALUES('129', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83147');
INSERT INTO `wp_woocommerce_order_items` VALUES('130', 'Бесплатная доставка (Почта РФ)', 'shipping', '83147');
INSERT INTO `wp_woocommerce_order_items` VALUES('135', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83148');
INSERT INTO `wp_woocommerce_order_items` VALUES('136', 'Бесплатная доставка (Почта РФ)', 'shipping', '83148');
INSERT INTO `wp_woocommerce_order_items` VALUES('137', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83149');
INSERT INTO `wp_woocommerce_order_items` VALUES('138', 'Бесплатная доставка (Почта РФ)', 'shipping', '83149');
INSERT INTO `wp_woocommerce_order_items` VALUES('147', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83150');
INSERT INTO `wp_woocommerce_order_items` VALUES('148', 'Пункт выдачи: бесплатно', 'shipping', '83150');
INSERT INTO `wp_woocommerce_order_items` VALUES('149', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83153');
INSERT INTO `wp_woocommerce_order_items` VALUES('150', 'Пункт выдачи: бесплатно', 'shipping', '83153');
INSERT INTO `wp_woocommerce_order_items` VALUES('151', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83154');
INSERT INTO `wp_woocommerce_order_items` VALUES('152', 'Пункт выдачи: бесплатно', 'shipping', '83154');
INSERT INTO `wp_woocommerce_order_items` VALUES('153', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83155');
INSERT INTO `wp_woocommerce_order_items` VALUES('154', 'Курьером до двери', 'shipping', '83155');
INSERT INTO `wp_woocommerce_order_items` VALUES('155', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83156');
INSERT INTO `wp_woocommerce_order_items` VALUES('156', 'Курьером до двери', 'shipping', '83156');
INSERT INTO `wp_woocommerce_order_items` VALUES('157', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83165');
INSERT INTO `wp_woocommerce_order_items` VALUES('158', 'Бесплатная доставка (Почта РФ)', 'shipping', '83165');
INSERT INTO `wp_woocommerce_order_items` VALUES('159', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83166');
INSERT INTO `wp_woocommerce_order_items` VALUES('160', 'Пункт выдачи: бесплатно', 'shipping', '83166');
INSERT INTO `wp_woocommerce_order_items` VALUES('161', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83167');
INSERT INTO `wp_woocommerce_order_items` VALUES('162', 'Пункт выдачи: бесплатно', 'shipping', '83167');
INSERT INTO `wp_woocommerce_order_items` VALUES('163', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83168');
INSERT INTO `wp_woocommerce_order_items` VALUES('164', 'Пункт выдачи: бесплатно', 'shipping', '83168');
INSERT INTO `wp_woocommerce_order_items` VALUES('165', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83172');
INSERT INTO `wp_woocommerce_order_items` VALUES('166', 'Курьер', 'shipping', '83172');
INSERT INTO `wp_woocommerce_order_items` VALUES('167', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83177');
INSERT INTO `wp_woocommerce_order_items` VALUES('168', 'Пункт выдачи: бесплатно', 'shipping', '83177');
INSERT INTO `wp_woocommerce_order_items` VALUES('169', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83178');
INSERT INTO `wp_woocommerce_order_items` VALUES('170', 'Курьером до двери', 'shipping', '83178');
INSERT INTO `wp_woocommerce_order_items` VALUES('171', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83179');
INSERT INTO `wp_woocommerce_order_items` VALUES('172', 'Курьером до двери', 'shipping', '83179');
INSERT INTO `wp_woocommerce_order_items` VALUES('173', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83180');
INSERT INTO `wp_woocommerce_order_items` VALUES('174', 'Бесплатная доставка (Почта РФ)', 'shipping', '83180');
INSERT INTO `wp_woocommerce_order_items` VALUES('175', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83181');
INSERT INTO `wp_woocommerce_order_items` VALUES('176', 'Бесплатная доставка (Почта РФ)', 'shipping', '83181');
INSERT INTO `wp_woocommerce_order_items` VALUES('177', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83184');
INSERT INTO `wp_woocommerce_order_items` VALUES('178', 'Пункт выдачи: бесплатно', 'shipping', '83184');
INSERT INTO `wp_woocommerce_order_items` VALUES('179', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83185');
INSERT INTO `wp_woocommerce_order_items` VALUES('180', 'Пункт выдачи: бесплатно', 'shipping', '83185');
INSERT INTO `wp_woocommerce_order_items` VALUES('181', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83186');
INSERT INTO `wp_woocommerce_order_items` VALUES('182', 'Пункт выдачи: бесплатно', 'shipping', '83186');
INSERT INTO `wp_woocommerce_order_items` VALUES('183', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83187');
INSERT INTO `wp_woocommerce_order_items` VALUES('184', 'Бесплатная доставка (Почта РФ)', 'shipping', '83187');
INSERT INTO `wp_woocommerce_order_items` VALUES('185', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83188');
INSERT INTO `wp_woocommerce_order_items` VALUES('186', 'Бесплатная доставка (Почта РФ)', 'shipping', '83188');
INSERT INTO `wp_woocommerce_order_items` VALUES('187', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83190');
INSERT INTO `wp_woocommerce_order_items` VALUES('188', 'Курьером до двери', 'shipping', '83190');
INSERT INTO `wp_woocommerce_order_items` VALUES('189', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83191');
INSERT INTO `wp_woocommerce_order_items` VALUES('190', 'Курьером до двери', 'shipping', '83191');
INSERT INTO `wp_woocommerce_order_items` VALUES('191', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83192');
INSERT INTO `wp_woocommerce_order_items` VALUES('192', 'Курьер', 'shipping', '83192');
INSERT INTO `wp_woocommerce_order_items` VALUES('193', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83193');
INSERT INTO `wp_woocommerce_order_items` VALUES('194', 'Пункт выдачи: бесплатно', 'shipping', '83193');
INSERT INTO `wp_woocommerce_order_items` VALUES('195', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83194');
INSERT INTO `wp_woocommerce_order_items` VALUES('196', 'Курьером до двери', 'shipping', '83194');
INSERT INTO `wp_woocommerce_order_items` VALUES('197', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83200');
INSERT INTO `wp_woocommerce_order_items` VALUES('198', 'Пункт выдачи: бесплатно', 'shipping', '83200');
INSERT INTO `wp_woocommerce_order_items` VALUES('199', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83201');
INSERT INTO `wp_woocommerce_order_items` VALUES('200', 'Пункт выдачи: бесплатно', 'shipping', '83201');
INSERT INTO `wp_woocommerce_order_items` VALUES('201', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83202');
INSERT INTO `wp_woocommerce_order_items` VALUES('202', 'Бесплатная доставка (Почта РФ)', 'shipping', '83202');
INSERT INTO `wp_woocommerce_order_items` VALUES('203', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83211');
INSERT INTO `wp_woocommerce_order_items` VALUES('204', 'Пункт выдачи: бесплатно', 'shipping', '83211');
INSERT INTO `wp_woocommerce_order_items` VALUES('205', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83212');
INSERT INTO `wp_woocommerce_order_items` VALUES('206', 'Бесплатная доставка (Почта РФ)', 'shipping', '83212');
INSERT INTO `wp_woocommerce_order_items` VALUES('207', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83213');
INSERT INTO `wp_woocommerce_order_items` VALUES('208', 'Курьером до двери', 'shipping', '83213');
INSERT INTO `wp_woocommerce_order_items` VALUES('209', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83214');
INSERT INTO `wp_woocommerce_order_items` VALUES('210', 'Курьером до двери', 'shipping', '83214');
INSERT INTO `wp_woocommerce_order_items` VALUES('211', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83215');
INSERT INTO `wp_woocommerce_order_items` VALUES('212', 'Курьером до двери', 'shipping', '83215');
INSERT INTO `wp_woocommerce_order_items` VALUES('213', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83216');
INSERT INTO `wp_woocommerce_order_items` VALUES('214', 'Бесплатная доставка (Почта РФ)', 'shipping', '83216');
INSERT INTO `wp_woocommerce_order_items` VALUES('215', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83217');
INSERT INTO `wp_woocommerce_order_items` VALUES('216', 'Курьером до двери', 'shipping', '83217');
INSERT INTO `wp_woocommerce_order_items` VALUES('217', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83218');
INSERT INTO `wp_woocommerce_order_items` VALUES('218', 'Бесплатная доставка (Почта РФ)', 'shipping', '83218');
INSERT INTO `wp_woocommerce_order_items` VALUES('219', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83219');
INSERT INTO `wp_woocommerce_order_items` VALUES('220', 'Бесплатная доставка (Почта РФ)', 'shipping', '83219');
INSERT INTO `wp_woocommerce_order_items` VALUES('221', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83220');
INSERT INTO `wp_woocommerce_order_items` VALUES('222', 'Бесплатная доставка (Почта РФ)', 'shipping', '83220');
INSERT INTO `wp_woocommerce_order_items` VALUES('223', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83221');
INSERT INTO `wp_woocommerce_order_items` VALUES('224', 'Пункт выдачи: бесплатно', 'shipping', '83221');
INSERT INTO `wp_woocommerce_order_items` VALUES('225', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83222');
INSERT INTO `wp_woocommerce_order_items` VALUES('226', 'Пункт выдачи: бесплатно', 'shipping', '83222');
INSERT INTO `wp_woocommerce_order_items` VALUES('227', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83223');
INSERT INTO `wp_woocommerce_order_items` VALUES('228', 'Курьером до двери', 'shipping', '83223');
INSERT INTO `wp_woocommerce_order_items` VALUES('229', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83224');
INSERT INTO `wp_woocommerce_order_items` VALUES('230', 'Курьером до двери', 'shipping', '83224');
INSERT INTO `wp_woocommerce_order_items` VALUES('231', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83225');
INSERT INTO `wp_woocommerce_order_items` VALUES('232', 'Бесплатная доставка (Почта РФ)', 'shipping', '83225');
INSERT INTO `wp_woocommerce_order_items` VALUES('233', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83226');
INSERT INTO `wp_woocommerce_order_items` VALUES('234', 'Курьером до двери', 'shipping', '83226');
INSERT INTO `wp_woocommerce_order_items` VALUES('235', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83227');
INSERT INTO `wp_woocommerce_order_items` VALUES('236', 'Курьер', 'shipping', '83227');
INSERT INTO `wp_woocommerce_order_items` VALUES('237', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83228');
INSERT INTO `wp_woocommerce_order_items` VALUES('238', 'Бесплатная доставка (Почта РФ)', 'shipping', '83228');
INSERT INTO `wp_woocommerce_order_items` VALUES('239', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83229');
INSERT INTO `wp_woocommerce_order_items` VALUES('240', 'Бесплатная доставка (Почта РФ)', 'shipping', '83229');
INSERT INTO `wp_woocommerce_order_items` VALUES('241', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83231');
INSERT INTO `wp_woocommerce_order_items` VALUES('242', 'Курьером до двери', 'shipping', '83231');
INSERT INTO `wp_woocommerce_order_items` VALUES('243', 'Пополнение баланса - 20€', 'line_item', '83233');
INSERT INTO `wp_woocommerce_order_items` VALUES('244', 'Пополнение баланса - 20€', 'line_item', '83234');
INSERT INTO `wp_woocommerce_order_items` VALUES('245', 'Пополнение баланса - 20€', 'line_item', '83235');
INSERT INTO `wp_woocommerce_order_items` VALUES('246', 'Пополнение баланса - 20€', 'line_item', '83236');
INSERT INTO `wp_woocommerce_order_items` VALUES('247', 'Пополнение баланса - 20€', 'line_item', '83238');
INSERT INTO `wp_woocommerce_order_items` VALUES('248', 'Fee for Банковские карты — Visa, Mastercard и Maestro, «Мир»:', 'fee', '83238');
INSERT INTO `wp_woocommerce_order_items` VALUES('249', 'Пополнение баланса - 20€', 'line_item', '83239');
INSERT INTO `wp_woocommerce_order_items` VALUES('250', 'Fee for Банковские карты — Visa, Mastercard и Maestro, «Мир»:', 'fee', '83239');
INSERT INTO `wp_woocommerce_order_items` VALUES('251', 'Пополнение баланса - 20€', 'line_item', '83240');
INSERT INTO `wp_woocommerce_order_items` VALUES('252', 'Fee for Банковские карты — Visa, Mastercard и Maestro, «Мир»:', 'fee', '83240');
INSERT INTO `wp_woocommerce_order_items` VALUES('253', 'Пополнение баланса - 20€', 'line_item', '83241');
INSERT INTO `wp_woocommerce_order_items` VALUES('254', 'Fee for Банковские карты — Visa, Mastercard и Maestro, «Мир»:', 'fee', '83241');
INSERT INTO `wp_woocommerce_order_items` VALUES('255', 'Пополнение баланса - 20€', 'line_item', '83242');
INSERT INTO `wp_woocommerce_order_items` VALUES('256', 'Fee for Банковские карты — Visa, Mastercard и Maestro, «Мир»:', 'fee', '83242');
INSERT INTO `wp_woocommerce_order_items` VALUES('257', 'Пополнение баланса - 20€', 'line_item', '83243');
INSERT INTO `wp_woocommerce_order_items` VALUES('258', 'Пополнение баланса - 20€', 'line_item', '83244');
INSERT INTO `wp_woocommerce_order_items` VALUES('259', 'Пополнение баланса - 20€', 'line_item', '83245');
INSERT INTO `wp_woocommerce_order_items` VALUES('260', 'Пополнение баланса - 20€', 'line_item', '83246');
INSERT INTO `wp_woocommerce_order_items` VALUES('261', 'Пополнение баланса - 20€', 'line_item', '83247');
INSERT INTO `wp_woocommerce_order_items` VALUES('262', 'Пополнение баланса - 20€', 'line_item', '83248');
INSERT INTO `wp_woocommerce_order_items` VALUES('263', 'Пополнение баланса - 20€', 'line_item', '83249');
INSERT INTO `wp_woocommerce_order_items` VALUES('264', 'Пополнение баланса - 20€', 'line_item', '83251');
INSERT INTO `wp_woocommerce_order_items` VALUES('265', 'test', 'fee', '83251');
INSERT INTO `wp_woocommerce_order_items` VALUES('266', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83252');
INSERT INTO `wp_woocommerce_order_items` VALUES('267', 'Курьером до двери', 'shipping', '83252');
INSERT INTO `wp_woocommerce_order_items` VALUES('268', 'Сим-карта Orange с тарифом Mundo', 'line_item', '83253');
INSERT INTO `wp_woocommerce_order_items` VALUES('269', 'Курьером до двери', 'shipping', '83253');
/*!40000 ALTER TABLE `wp_woocommerce_order_items` ENABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS = 1;
