CREATE TABLE `wp_yoast_seo_links` (  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,  `url` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,  `post_id` bigint(20) unsigned NOT NULL,  `target_post_id` bigint(20) unsigned NOT NULL,  `type` varchar(8) COLLATE utf8mb4_unicode_ci NOT NULL,  PRIMARY KEY (`id`),  KEY `link_direction` (`post_id`,`type`)) ENGINE=InnoDB AUTO_INCREMENT=553 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40000 ALTER TABLE `wp_yoast_seo_links` DISABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 0;
SET UNIQUE_CHECKS = 0;
INSERT INTO `wp_yoast_seo_links` VALUES('470', 'https://ayuda.orange.es/particulares/movil/roaming-internacional/2314-si-vas-a-viajar-fuera-de-la-union-europea-no-olvides-activar-everywhere', '83082', '0', 'external');
INSERT INTO `wp_yoast_seo_links` VALUES('541', '\\', '1049', '0', 'internal');
INSERT INTO `wp_yoast_seo_links` VALUES('542', '\\', '1049', '0', 'internal');
INSERT INTO `wp_yoast_seo_links` VALUES('543', 'https://orange.es/', '5', '0', 'external');
INSERT INTO `wp_yoast_seo_links` VALUES('544', 'https://orange.es/', '5', '0', 'external');
INSERT INTO `wp_yoast_seo_links` VALUES('545', 'https://orange.es/', '5', '0', 'external');
INSERT INTO `wp_yoast_seo_links` VALUES('546', 'https://orange.es/', '5', '0', 'external');
INSERT INTO `wp_yoast_seo_links` VALUES('547', 'https://euroroaming.ru/instruction-orange-go-europe/', '5', '0', 'external');
INSERT INTO `wp_yoast_seo_links` VALUES('548', 'https://ayuda.orange.es/particulares/movil/roaming-internacional/2314-si-vas-a-viajar-fuera-de-la-union-europea-no-olvides-activar-everywhere', '5', '0', 'external');
INSERT INTO `wp_yoast_seo_links` VALUES('549', 'tel:+74993220824', '5', '0', 'external');
INSERT INTO `wp_yoast_seo_links` VALUES('550', 'tel:+78123171825', '5', '0', 'external');
INSERT INTO `wp_yoast_seo_links` VALUES('551', 'https://ayuda.orange.es/particulares/movil/roaming-internacional/2314-si-vas-a-viajar-fuera-de-la-union-europea-no-olvides-activar-everywhere', '5', '0', 'external');
INSERT INTO `wp_yoast_seo_links` VALUES('552', 'https://orangesim.ru/product/popolnenie-balansa/?attribute_balans-karty=20%E2%82%AC&amp;variation_id=1397&amp;add-to-cart=1395', '5', '1395', 'internal');
/*!40000 ALTER TABLE `wp_yoast_seo_links` ENABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS = 1;
